"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.2.11.
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# 1. Define BASE_DIR first (Required for load_dotenv to work)
BASE_DIR = Path(__file__).resolve().parent.parent

# 2. Load environment variables from the .env file in the backend root
load_dotenv(os.path.join(BASE_DIR, '.env'))

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['out-of-context-167456099297.us-central1.run.app']

# Application definition
INSTALLED_APPS = [
    'corsheaders',  # Required for React to talk to Django
    'game',         # Your custom app
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # MUST be at the top
    'django.middleware.security.SecurityMiddleware',
    'django.middleware.common.CommonMiddleware',
]

# 4. CORS configuration
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = ['https://outofcontext.vercel.app']

ROOT_URLCONF = 'server.urls'

WSGI_APPLICATION = 'server.wsgi.application'

# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True